/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pa_23130550_proyecto_04;

import java.awt.Color;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.DecimalFormat;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author migue
 */
public class PA_23130550_Frame_04 extends javax.swing.JFrame {

    /**
     * Creates new form PA_23130550_Frame_01
     */
    private DefaultTableModel modelo;
    private JFileChooser jfch = new JFileChooser(); // creacion de objeto JFileChooser
    private Color color; 
    
    public PA_23130550_Frame_04() {
        initComponents();
        modelo = (DefaultTableModel) jTableVehiculos.getModel();        
        jTableVehiculos.setShowGrid(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVehiculos = new javax.swing.JTable();
        jLabPromedio = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButCalcular = new javax.swing.JButton();
        jSpinVehiculos = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jButAleatorios = new javax.swing.JButton();
        jButEjemplo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemNuevo = new javax.swing.JMenuItem();
        jMenuItemAbrir = new javax.swing.JMenuItem();
        jMenuItemGuardar = new javax.swing.JMenuItem();
        jMenuItemGuardarAlfabetico = new javax.swing.JMenuItem();
        jMenuItemCerrar = new javax.swing.JMenuItem();
        jMenuEditarColor = new javax.swing.JMenu();
        jMenuItemColorBotones = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asignacion2024.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asignacionp4.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableVehiculos.setBackground(new java.awt.Color(255, 255, 255));
        jTableVehiculos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2));
        jTableVehiculos.setFont(new java.awt.Font("Roboto Light", 0, 17)); // NOI18N
        jTableVehiculos.setForeground(new java.awt.Color(102, 102, 102));
        jTableVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehículo", "Distancia", "Aceleración", "Tiempo", "V. Inicial"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVehiculos.setFocusable(false);
        jTableVehiculos.setRowHeight(25);
        jTableVehiculos.setSelectionBackground(new java.awt.Color(51, 51, 255));
        jTableVehiculos.setShowHorizontalLines(true);
        jTableVehiculos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableVehiculos);

        jLabPromedio.setBackground(new java.awt.Color(204, 204, 204));
        jLabPromedio.setFont(new java.awt.Font("Roboto Medium", 1, 19)); // NOI18N
        jLabPromedio.setForeground(new java.awt.Color(51, 51, 255));
        jLabPromedio.setOpaque(true);

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 19)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Vi Promedio: ");

        jButCalcular.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButCalcular.setText("Calcular");
        jButCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalcularActionPerformed(evt);
            }
        });

        jSpinVehiculos.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        jSpinVehiculos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinVehiculosStateChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 19)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("N° Vehiculos: ");

        jButAleatorios.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButAleatorios.setText("Aleatorios");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jButEjemplo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButEjemplo.setText("Ejemplo");
        jButEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemploActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("M.R.U.");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pootabla.png"))); // NOI18N

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel1)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButAleatorios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButEjemplo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButCalcular)
                            .addComponent(jButAleatorios)
                            .addComponent(jButEjemplo))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 102));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        jMenuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/299048_folder_document_icon.png"))); // NOI18N
        jMenuArchivo.setText("Archivo");
        jMenuArchivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItemNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemNuevo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2303108_write_new_document_create_icon.png"))); // NOI18N
        jMenuItemNuevo.setText("Nuevo");
        jMenuItemNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevoActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemNuevo);

        jMenuItemAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemAbrir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/7472_blue_folder_open_icon.png"))); // NOI18N
        jMenuItemAbrir.setText("Abrir");
        jMenuItemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbrirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemAbrir);

        jMenuItemGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemGuardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/285657_floppy_guardar_save_icon.png"))); // NOI18N
        jMenuItemGuardar.setText("Guardar");
        jMenuItemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemGuardar);

        jMenuItemGuardarAlfabetico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemGuardarAlfabetico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemGuardarAlfabetico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1553073_abc_letter_alphabet_letters_icon.png"))); // NOI18N
        jMenuItemGuardarAlfabetico.setText("Guardar Alfabetico");
        jMenuItemGuardarAlfabetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardarAlfabeticoActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemGuardarAlfabetico);

        jMenuItemCerrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2142693_arrow_close_door_exit_out_icon.png"))); // NOI18N
        jMenuItemCerrar.setText("Cerrar");
        jMenuItemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCerrarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemCerrar);

        jMenuBar1.add(jMenuArchivo);

        jMenuEditarColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/17022_colors_draw_paint_icon.png"))); // NOI18N
        jMenuEditarColor.setText("Editar Color");
        jMenuEditarColor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItemColorBotones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemColorBotones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/8675449_ic_fluent_text_color_regular_icon.png"))); // NOI18N
        jMenuItemColorBotones.setText("Texto Botones");
        jMenuItemColorBotones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemColorBotonesActionPerformed(evt);
            }
        });
        jMenuEditarColor.add(jMenuItemColorBotones);

        jMenuBar1.add(jMenuEditarColor);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinVehiculosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinVehiculosStateChanged
        // TODO add your handling code here:
        int renglones = (int)jSpinVehiculos.getValue();

        modelo.setRowCount(renglones);
    }//GEN-LAST:event_jSpinVehiculosStateChanged

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        // TODO add your handling code here:
        Random azar = new Random();
        DecimalFormat formato = new DecimalFormat("#,###,##0.00");
        
        jLabPromedio.setText("");
        
        String [] vehiculo = {"Vocho","Mustang","Cheyenne","BMW","Ferrari" ,"Fiesta","Chevy","Tsuru","Volvo","RAM","Lamborgini","Bugatti","Botemovil","Triangulo Rojo"};

        for(int r=0; r < jTableVehiculos.getRowCount(); r++) {
            jTableVehiculos.setValueAt(null, r, 4);            
            jTableVehiculos.setValueAt(vehiculo[azar.nextInt(vehiculo.length)],r,0);
            // se colocan datos pequeños para evitar Vo negativas
            jTableVehiculos.setValueAt(formato.format(azar.nextDouble(100, 1000)), r, 1) ; // distancia
            jTableVehiculos.setValueAt(formato.format(azar.nextDouble(-2, 5)), r, 2); // aceleracion
            jTableVehiculos.setValueAt(formato.format(azar.nextDouble(5, 30)), r, 3); // tiempo

        }
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jButEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemploActionPerformed
        // TODO add your handling code here:
        modelo.setRowCount(5);

        // Descripcion
        jTableVehiculos.setValueAt("Mustang",  0, 0);
        jTableVehiculos.setValueAt("Cheyenne",  1, 0);
        jTableVehiculos.setValueAt("BMW",  2, 0);
        jTableVehiculos.setValueAt("Vocho",  3, 0);
        jTableVehiculos.setValueAt("Ferrari",  4, 0);

        // Distancia
        jTableVehiculos.setValueAt(113400,  0, 1);
        jTableVehiculos.setValueAt(31500,  1, 1);
        jTableVehiculos.setValueAt(113400,  2, 1);
        jTableVehiculos.setValueAt(45825,  3, 1);
        jTableVehiculos.setValueAt(113400,  4, 1);

        // Aceleracion
        jTableVehiculos.setValueAt(15,  0, 2);
        jTableVehiculos.setValueAt(30,  1, 2);
        jTableVehiculos.setValueAt(15,  2, 2);
        jTableVehiculos.setValueAt(20,  3, 2);
        jTableVehiculos.setValueAt(15,  4, 2);

        // tiempo
        jTableVehiculos.setValueAt(120,  0, 3);
        jTableVehiculos.setValueAt(45,  1, 3);
        jTableVehiculos.setValueAt(120,  2, 3);
        jTableVehiculos.setValueAt(65,  3, 3);
        jTableVehiculos.setValueAt(120,  4, 3);
    }//GEN-LAST:event_jButEjemploActionPerformed

    private void jButCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalcularActionPerformed
        // TODO add your handling code here:
        Garaje garaje = new Garaje(jTableVehiculos);
        // se manda a llamar el metodo mostrar a traves de garaje
        garaje.mostrar(jTableVehiculos, jLabPromedio);
    }//GEN-LAST:event_jButCalcularActionPerformed

    private void jMenuItemColorBotonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemColorBotonesActionPerformed
        // TODO add your handling code here:       
        // Se abre un dialogo del JColorChooser para seleccionar un color.        
        color = JColorChooser.showDialog(this, "Selecciona un color de fuente para los botones", color);
        
        // Si no se selecciona ningún color, el color se establece en negro.        
        if (color == null) {
            color = Color.BLACK;  
        }
        
        // Si se selecciona un color, se establece ese color como el color de fuente de los botones 
        if (color != null) {
            jButCalcular.setForeground(color);
            jButAleatorios.setForeground(color);
            jButEjemplo.setForeground(color);
        }
               
    }//GEN-LAST:event_jMenuItemColorBotonesActionPerformed

    private void jMenuItemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarActionPerformed
        // Se muestra un cuadro de diálogo de guardar archivo. Si se cancela la operación, el método finaliza su ejecución.
        if (jfch.showSaveDialog(jLabel1) != 0) 
            return;
        
        // Declaración de los flujos de salida
        FileOutputStream fos = null;
        DataOutputStream dos = null;
        ObjectOutputStream oos = null;
        
        try {
            fos = new FileOutputStream(jfch.getSelectedFile());
            dos = new DataOutputStream(fos);
            oos = new ObjectOutputStream(fos);
            
            // Escribe el número de filas del modelo en el archivo.
            dos.writeInt(modelo.getRowCount());
            
            for (int r = 0; r < modelo.getRowCount(); r++) {
                // Escribe el valor de la primera columna (vehículo) como una cadena de texto.                
                dos.writeUTF(modelo.getValueAt(r, 0) + ""); // vehiculo
                
                for (int c = 1; c <= 3; c++) {
                    // Itera sobre las columnas 1 a 3 y escribe cada valor como un double.                   
                    dos.writeDouble(Double.parseDouble(modelo.getValueAt(r, c) + ""));
                }
            }
            // Escribe el color de la fuente del botón jButCalcular como un objeto.
            oos.writeObject(jButCalcular.getForeground());
            JOptionPane.showMessageDialog(rootPane, "Archivo guardado");
            
        } catch (FileNotFoundException ex) {
            // Maneja la excepción si el archivo no se encuentra.
            Logger.getLogger(PA_23130550_Frame_04.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PA_23130550_Frame_04.class.getName()).log(Level.SEVERE, null, ex);
        } finally { 
            // se cierran los flujos de salida si no son null.
            try {
                if(dos != null)
                    dos.close();
                if(fos != null)
                    fos.close();
            } catch (IOException ex) {
                Logger.getLogger(PA_23130550_Frame_04.class.getName()).log(Level.SEVERE, null, ex);
            }
        }     
        
    }//GEN-LAST:event_jMenuItemGuardarActionPerformed

    private void jMenuItemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrarActionPerformed
        // cierra la ventana actual
        this.dispose();
    }//GEN-LAST:event_jMenuItemCerrarActionPerformed

    private void jMenuItemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoActionPerformed
        // Establece valores nulos en el color de texto de los botones
        jButCalcular.setForeground(null);
        jButEjemplo.setForeground(null);
        jButAleatorios.setForeground(null);
        
        // Establece el JSpin en 0, y borra el contenido de la etiqueta
        jSpinVehiculos.setValue(0);
        jLabPromedio.setText("");
    }//GEN-LAST:event_jMenuItemNuevoActionPerformed

    private void jMenuItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirActionPerformed
        // Se muestra un cuadro de diálogo para abrir un archivo. Si se cancela la operación, el método termina.
        if(jfch.showOpenDialog(jLabel1) != 0)
            return;
        
        // Declaracion de flujos de entrada
        FileInputStream fis = null;
        DataInputStream dis = null;
        ObjectInputStream ois = null;
        
        try {
            fis = new FileInputStream(jfch.getSelectedFile());
            dis = new DataInputStream(fis);
            ois = new ObjectInputStream(fis);
            
             // Lee el número de vehículos y lo establece en el jSpinVehiculos.
             jSpinVehiculos.setValue(dis.readInt());           
            
            for (int r = 0; r < modelo.getRowCount(); r++) {
                // Lee el valor de la primera columna (vehículo) como una cadena de texto.
                modelo.setValueAt(dis.readUTF(),r,0); // vehiculo
                
                // Itera sobre las columnas 1 a 3 y lee cada valor como un double.
                for (int c = 1; c <= 3; c++) {
                    modelo.setValueAt(dis.readDouble(),r,c);
                }
            }
            
            // Lee el color de la fuente del botón y lo establece.
            jButCalcular.setForeground((Color)ois.readObject());
            color = jButCalcular.getForeground();
            // Establece el mismo color de fuente para los demas botones.
            jButAleatorios.setForeground(color);
            jButEjemplo.setForeground(color);
            
            // se ejecuta el evento del boton calcular
            jButCalcular.doClick();
             
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PA_23130550_Frame_04.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PA_23130550_Frame_04.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PA_23130550_Frame_04.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            // se cierran los flujos de entrada si no son null.
            try {
                if(dis != null)
                    dis.close();
                if(fis != null)
                    fis.close();
            } catch (IOException ex) {
                Logger.getLogger(PA_23130550_Frame_04.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jMenuItemAbrirActionPerformed

    private void jMenuItemGuardarAlfabeticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarAlfabeticoActionPerformed
        Garaje garaje = new Garaje(jTableVehiculos);       
        // Se ordenan los vehículos de forma alfabética.
        garaje.alfabetico();        
        
         // Se obtiene la lista de vehículos ordenada alfabéticamente.
        Vehiculo[] listaOrdenada = garaje.getLista();
        
        // Se muestra un cuadro de diálogo para guardar el archivo. Si se cancela la operación, el método finaliza.
        if (jfch.showSaveDialog(jLabel1) != 0) 
            return;
        FileOutputStream fos = null;
        DataOutputStream dos = null;
        ObjectOutputStream oos = null;
        
        try {
            fos = new FileOutputStream(jfch.getSelectedFile());
            dos = new DataOutputStream(fos);
            oos = new ObjectOutputStream(fos);
            
            // Se escribe la cantidad de vehículos en el archivo.           
            dos.writeInt(listaOrdenada.length);
            
            // Itera sobre cada vehículo en la lista ordenada y escribe sus datos en el archivo.            
            for (Vehiculo vehiculo : listaOrdenada) {
                dos.writeUTF(vehiculo.getDescripcion()); // Escribe la descripción del vehículo como una cadena de texto.
                 // Escribe la distancia, aceleración y tiempo del vehículo como double.
                dos.writeDouble(vehiculo.getDistancia());
                dos.writeDouble(vehiculo.getAceleracion());
                dos.writeDouble(vehiculo.getTiempo());               
            }
            // Escribe el color de la fuente del botón jButCalcular en el archivo.
            oos.writeObject(jButCalcular.getForeground());
            JOptionPane.showMessageDialog(rootPane, "Archivo guardado");
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PA_23130550_Frame_04.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PA_23130550_Frame_04.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            // se cierran los flujos de salida si no son null.
            try {
                if(dos != null)
                    dos.close();
                if(fos != null)
                    fos.close();
            } catch (IOException ex) {
                Logger.getLogger(PA_23130550_Frame_04.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jMenuItemGuardarAlfabeticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PA_23130550_Frame_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PA_23130550_Frame_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PA_23130550_Frame_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PA_23130550_Frame_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PA_23130550_Frame_04().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButCalcular;
    private javax.swing.JButton jButEjemplo;
    private javax.swing.JLabel jLabPromedio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEditarColor;
    private javax.swing.JMenuItem jMenuItemAbrir;
    private javax.swing.JMenuItem jMenuItemCerrar;
    private javax.swing.JMenuItem jMenuItemColorBotones;
    private javax.swing.JMenuItem jMenuItemGuardar;
    private javax.swing.JMenuItem jMenuItemGuardarAlfabetico;
    private javax.swing.JMenuItem jMenuItemNuevo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinVehiculos;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableVehiculos;
    // End of variables declaration//GEN-END:variables
}
